---
Name: goldfinch-enchantment
After:
  - '#goldfinch-basement'
  - '#goldfinch-seokit'
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Enchantment\Extensions\SiteConfigExtension

SilverStripe\Admin\LeftAndMain:
  extensions:
    - Goldfinch\Enchantment\Extensions\EnchantmentAssetsExtension

SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - '/build-cms/enchantment/assets/wysiwyg.css'
