---
Name: goldfinch-enchantment
After:
  - '#goldfinch-basement'
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Goldfinch\Enchantment\Extensions\SiteConfigExtension

SilverStripe\Admin\LeftAndMain:
  extensions:
    - Goldfinch\Enchantment\Extensions\EnchantmentAssetExtension
